# Generated by Django 3.1.2 on 2020-11-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(blank=True, max_length=255, null=True)),
                ('commentsDiscipline', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchEstablishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory', models.CharField(blank=True, max_length=255, null=True)),
                ('establishment', models.CharField(blank=True, max_length=255, null=True)),
                ('commentsEstablishment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researchField', models.CharField(blank=True, max_length=255, null=True)),
                ('commentsResearch', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postalAdress', models.IntegerField(blank=True, null=True)),
                ('phoneNumber', models.IntegerField(blank=True, null=True)),
                ('profileImage', models.URLField(blank=True, null=True)),
                ('workedOnTheSite', models.BooleanField(default=False)),
                ('workedInCompany', models.CharField(blank=True, max_length=255, null=True)),
                ('workTimeDuration', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
