# Generated by Django 3.1.2 on 2020-10-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('viability', models.IntegerField(choices=[(0, 'Notreliable'), (1, 'Reliable')])),
                ('conservation_place', models.CharField(max_length=500)),
                ('cote', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('definition', models.CharField(max_length=500)),
                ('autonomous', models.BooleanField(default=False)),
                ('source', models.ManyToManyField(to='database.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sexe', models.BooleanField()),
                ('profession', models.ManyToManyField(to='database.Profession')),
                ('source', models.ManyToManyField(to='database.Source')),
            ],
        ),
    ]
