# Generated by Django 3.1.2 on 2020-10-23 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20201023_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.place'),
        ),
    ]
