# Generated by Django 3.1.2 on 2020-10-23 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20201023_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='place',
            field=models.ManyToManyField(to='database.Place'),
        ),
        migrations.AddField(
            model_name='social',
            name='place',
            field=models.ManyToManyField(to='database.Place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.placelocation'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.placetype'),
        ),
    ]
