# Generated by Django 3.1.2 on 2020-10-26 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20201026_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractobject',
            name='collectiveActor',
            field=models.ManyToManyField(to='database.CollectiveActor'),
        ),
        migrations.AddField(
            model_name='abstractobject',
            name='date',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.date'),
        ),
        migrations.AddField(
            model_name='abstractobject',
            name='knowledge',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.knowledge'),
        ),
        migrations.AddField(
            model_name='abstractobject',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.place'),
        ),
        migrations.AddField(
            model_name='abstractobject',
            name='quality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.quality'),
        ),
        migrations.AddField(
            model_name='abstractobject',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.source'),
        ),
        migrations.AddField(
            model_name='actor',
            name='collectiveActors',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.collectiveactor'),
        ),
        migrations.AddField(
            model_name='actor',
            name='place',
            field=models.ManyToManyField(to='database.Place'),
        ),
        migrations.AddField(
            model_name='actor',
            name='profession',
            field=models.ManyToManyField(to='database.Profession'),
        ),
        migrations.AddField(
            model_name='actor',
            name='quality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.quality'),
        ),
        migrations.AddField(
            model_name='actor',
            name='social',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.social'),
        ),
        migrations.AddField(
            model_name='actor',
            name='socialLink',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.sociallink'),
        ),
        migrations.AddField(
            model_name='actor',
            name='source',
            field=models.ManyToManyField(to='database.Source'),
        ),
        migrations.AddField(
            model_name='caracteristics',
            name='detail_caracteristics',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.detailcaracteristics'),
        ),
        migrations.AddField(
            model_name='collectiveactor',
            name='date',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.date'),
        ),
        migrations.AddField(
            model_name='collectiveactor',
            name='knowledge',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.knowledge'),
        ),
        migrations.AddField(
            model_name='collectiveactor',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.place'),
        ),
        migrations.AddField(
            model_name='collectiveactor',
            name='quality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.quality'),
        ),
        migrations.AddField(
            model_name='collectiveactor',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.source'),
        ),
        migrations.AddField(
            model_name='nameactor',
            name='actor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.actor'),
        ),
        migrations.AddField(
            model_name='object',
            name='abstract_object',
            field=models.ManyToManyField(to='database.AbstractObject'),
        ),
        migrations.AddField(
            model_name='object',
            name='actor',
            field=models.ManyToManyField(to='database.Actor'),
        ),
        migrations.AddField(
            model_name='object',
            name='caracteristics',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.caracteristics'),
        ),
        migrations.AddField(
            model_name='object',
            name='collectiveActors',
            field=models.ManyToManyField(to='database.CollectiveActor'),
        ),
        migrations.AddField(
            model_name='object',
            name='energy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.energy'),
        ),
        migrations.AddField(
            model_name='object',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.place'),
        ),
        migrations.AddField(
            model_name='object',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.source'),
        ),
        migrations.AddField(
            model_name='object',
            name='type_object',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.typeobject'),
        ),
        migrations.AddField(
            model_name='place',
            name='place_location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.placelocation'),
        ),
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.placetype'),
        ),
        migrations.AddField(
            model_name='place',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.source'),
        ),
        migrations.AddField(
            model_name='profession',
            name='abstractobjects',
            field=models.ManyToManyField(to='database.AbstractObject'),
        ),
        migrations.AddField(
            model_name='profession',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.place'),
        ),
        migrations.AddField(
            model_name='profession',
            name='source',
            field=models.ManyToManyField(to='database.Source'),
        ),
        migrations.AddField(
            model_name='social',
            name='place',
            field=models.ManyToManyField(to='database.Place'),
        ),
        migrations.AddField(
            model_name='social',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.source'),
        ),
        migrations.AddField(
            model_name='source',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.author'),
        ),
        migrations.AddField(
            model_name='source',
            name='content',
            field=models.ManyToManyField(to='database.Content'),
        ),
        migrations.AddField(
            model_name='source',
            name='date',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.date'),
        ),
        migrations.AddField(
            model_name='source',
            name='types',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.types'),
        ),
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.ManyToManyField(to='database.Url'),
        ),
    ]
