# Generated by Django 3.1.2 on 2020-10-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20201026_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeobject',
            name='typeObject',
            field=models.CharField(max_length=100),
        ),
    ]
