# Generated by Django 3.1.2 on 2020-10-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20201026_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_location',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='database.placelocation'),
        ),
        migrations.AlterField(
            model_name='source',
            name='content',
            field=models.ManyToManyField(blank=True, to='database.Content'),
        ),
    ]
