# Generated by Django 3.1.2 on 2020-10-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20201026_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='place',
            field=models.ManyToManyField(blank=True, to='database.Place'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='profession',
            field=models.ManyToManyField(blank=True, to='database.Profession'),
        ),
    ]
