# Generated by Django 3.1.2 on 2020-10-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_auto_20201026_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='abstractobjects',
            field=models.ManyToManyField(blank=True, to='database.AbstractObject'),
        ),
    ]
