# Generated by Django 3.1.2 on 2020-10-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_auto_20201026_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='abstract_object',
            field=models.ManyToManyField(blank=True, to='database.AbstractObject'),
        ),
        migrations.AlterField(
            model_name='object',
            name='actor',
            field=models.ManyToManyField(blank=True, to='database.Actor'),
        ),
        migrations.AlterField(
            model_name='object',
            name='collectiveActors',
            field=models.ManyToManyField(blank=True, to='database.CollectiveActor'),
        ),
        migrations.AlterField(
            model_name='object',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='energy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.energy'),
        ),
        migrations.AlterField(
            model_name='object',
            name='place',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.place'),
        ),
    ]
