# Generated by Django 3.1.2 on 2020-10-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_auto_20201026_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placelocation',
            name='lieu_dit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='placelocation',
            name='post_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='placelocation',
            name='street_type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
