# Generated by Django 3.1.2 on 2020-10-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_auto_20201026_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialActivitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('definition', models.CharField(max_length=500)),
                ('place', models.ManyToManyField(blank=True, to='database.Place')),
                ('source', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.source')),
            ],
        ),
        migrations.RemoveField(
            model_name='actor',
            name='social',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
        migrations.AddField(
            model_name='actor',
            name='socialActivities',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.socialactivitie'),
        ),
    ]
