# Generated by Django 3.1.2 on 2020-10-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_auto_20201026_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracteristic',
            old_name='nameCaracteristic',
            new_name='objectCaracteristic',
        ),
    ]
