# Generated by Django 3.1.2 on 2020-10-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0041_auto_20201027_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='socialLink',
            new_name='Link',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='actors',
            field=models.ManyToManyField(to='database.Actor'),
        ),
    ]
