# Generated by Django 3.1.2 on 2020-10-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0042_auto_20201027_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='actors',
            new_name='actorlinked',
        ),
        migrations.RenameField(
            model_name='sociallink',
            old_name='Link',
            new_name='link',
        ),
    ]
