# Generated by Django 3.1.2 on 2020-10-27 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0043_auto_20201027_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nameactor',
            old_name='actor',
            new_name='actors',
        ),
        migrations.AddField(
            model_name='actor',
            name='namesOfActor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.nameactor'),
        ),
    ]
