# Generated by Django 3.1.2 on 2020-10-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0049_auto_20201028_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placelocation',
            old_name='lieu_dit',
            new_name='place_said',
        ),
    ]
