# Generated by Django 3.1.2 on 2020-10-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0050_auto_20201029_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profession',
            old_name='abstractobjects',
            new_name='abstractObject',
        ),
    ]
