# Generated by Django 3.1.2 on 2020-10-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0051_auto_20201029_0852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailCaracteristics',
            new_name='DetailCaracteristic',
        ),
    ]
