# Generated by Django 3.1.2 on 2020-11-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0052_auto_20201029_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='date',
            field=models.ManyToManyField(blank=True, to='database.Date'),
        ),
        migrations.RemoveField(
            model_name='abstractobject',
            name='date',
        ),
        migrations.AddField(
            model_name='abstractobject',
            name='date',
            field=models.ManyToManyField(blank=True, to='database.Date'),
        ),
        migrations.RemoveField(
            model_name='abstractobject',
            name='knowledge',
        ),
        migrations.AddField(
            model_name='abstractobject',
            name='knowledge',
            field=models.ManyToManyField(blank=True, to='database.Knowledge'),
        ),
        migrations.RemoveField(
            model_name='abstractobject',
            name='place',
        ),
        migrations.AddField(
            model_name='abstractobject',
            name='place',
            field=models.ManyToManyField(blank=True, to='database.Place'),
        ),
        migrations.RemoveField(
            model_name='abstractobject',
            name='quality',
        ),
        migrations.AddField(
            model_name='abstractobject',
            name='quality',
            field=models.ManyToManyField(blank=True, to='database.Quality'),
        ),
        migrations.RemoveField(
            model_name='abstractobject',
            name='source',
        ),
        migrations.AddField(
            model_name='abstractobject',
            name='source',
            field=models.ManyToManyField(to='database.Source'),
        ),
        migrations.RemoveField(
            model_name='actor',
            name='collectiveActors',
        ),
        migrations.AddField(
            model_name='actor',
            name='collectiveActors',
            field=models.ManyToManyField(blank=True, to='database.CollectiveActor'),
        ),
        migrations.RemoveField(
            model_name='actor',
            name='quality',
        ),
        migrations.AddField(
            model_name='actor',
            name='quality',
            field=models.ManyToManyField(blank=True, to='database.Quality'),
        ),
        migrations.RemoveField(
            model_name='actor',
            name='socialActivities',
        ),
        migrations.AddField(
            model_name='actor',
            name='socialActivities',
            field=models.ManyToManyField(blank=True, to='database.SocialActivitie'),
        ),
        migrations.RemoveField(
            model_name='actor',
            name='socialLink',
        ),
        migrations.AddField(
            model_name='actor',
            name='socialLink',
            field=models.ManyToManyField(blank=True, to='database.SocialLink'),
        ),
        migrations.RemoveField(
            model_name='caracteristic',
            name='detail_caracteristics',
        ),
        migrations.AddField(
            model_name='caracteristic',
            name='detail_caracteristics',
            field=models.ManyToManyField(blank=True, to='database.DetailCaracteristic'),
        ),
        migrations.RemoveField(
            model_name='caracteristic',
            name='source',
        ),
        migrations.AddField(
            model_name='caracteristic',
            name='source',
            field=models.ManyToManyField(to='database.Source'),
        ),
        migrations.RemoveField(
            model_name='collectiveactor',
            name='date',
        ),
        migrations.AddField(
            model_name='collectiveactor',
            name='date',
            field=models.ManyToManyField(blank=True, to='database.Date'),
        ),
        migrations.RemoveField(
            model_name='collectiveactor',
            name='knowledge',
        ),
        migrations.AddField(
            model_name='collectiveactor',
            name='knowledge',
            field=models.ManyToManyField(blank=True, to='database.Knowledge'),
        ),
        migrations.RemoveField(
            model_name='collectiveactor',
            name='place',
        ),
        migrations.AddField(
            model_name='collectiveactor',
            name='place',
            field=models.ManyToManyField(blank=True, to='database.Place'),
        ),
        migrations.RemoveField(
            model_name='collectiveactor',
            name='quality',
        ),
        migrations.AddField(
            model_name='collectiveactor',
            name='quality',
            field=models.ManyToManyField(blank=True, to='database.Quality'),
        ),
        migrations.RemoveField(
            model_name='collectiveactor',
            name='source',
        ),
        migrations.AddField(
            model_name='collectiveactor',
            name='source',
            field=models.ManyToManyField(to='database.Source'),
        ),
        migrations.RemoveField(
            model_name='object',
            name='place',
        ),
        migrations.AddField(
            model_name='object',
            name='place',
            field=models.ManyToManyField(blank=True, to='database.Place'),
        ),
        migrations.RemoveField(
            model_name='object',
            name='source',
        ),
        migrations.AddField(
            model_name='object',
            name='source',
            field=models.ManyToManyField(to='database.Source'),
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_type',
        ),
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.ManyToManyField(blank=True, to='database.PlaceType'),
        ),
        migrations.RemoveField(
            model_name='place',
            name='source',
        ),
        migrations.AddField(
            model_name='place',
            name='source',
            field=models.ManyToManyField(to='database.Source'),
        ),
        migrations.RemoveField(
            model_name='socialactivitie',
            name='source',
        ),
        migrations.AddField(
            model_name='socialactivitie',
            name='source',
            field=models.ManyToManyField(to='database.Source'),
        ),
        migrations.RemoveField(
            model_name='source',
            name='date',
        ),
        migrations.AddField(
            model_name='source',
            name='date',
            field=models.ManyToManyField(blank=True, to='database.Date'),
        ),
    ]
