# Generated by Django 3.1.2 on 2020-11-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0053_auto_20201104_1045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialActivitie',
            new_name='SocialActivity',
        ),
    ]
