# Generated by Django 3.1.2 on 2020-11-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0054_auto_20201104_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.ManyToManyField(blank=True, to='database.Url'),
        ),
    ]
