# Generated by Django 3.1.2 on 2020-11-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0055_auto_20201117_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='cote',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='source',
            name='viability',
            field=models.IntegerField(choices=[(0, 'Notreliable'), (1, 'Reliable')], default=0),
        ),
    ]
