# Generated by Django 3.1.2 on 2021-01-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0058_auto_20210106_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_table', models.CharField(choices=[('Date', 'Date'), ('Quality', 'Quality'), ('SourceType', 'Sourcetype'), ('Author', 'Author'), ('Content', 'Content'), ('Url', 'Url'), ('Source', 'Source'), ('PlaceLocation', 'Placelocation'), ('PlaceType', 'Placetype'), ('Place', 'Place'), ('Knowledge', 'Knowledge'), ('CollectiveActor', 'Collectiveactor'), ('AbstractObject', 'Abstractobject'), ('Profession', 'Profession'), ('SocialActivity', 'Socialactivity'), ('SocialLink', 'Sociallink'), ('Actor', 'Actor'), ('NameActor', 'Nameactor'), ('DetailCaracteristic', 'Detailcaracteristic'), ('TypeObject', 'Typeobject'), ('Energy', 'Energy'), ('Object', 'Object'), ('Caracteristic', 'Caracteristic')], max_length=250)),
                ('id_fk', models.IntegerField()),
                ('ressource_title', models.CharField(max_length=1000)),
            ],
        ),
    ]
