# Generated by Django 3.1.2 on 2021-01-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
