# Generated by Django 3.1.2 on 2020-12-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20201211_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postalAdress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
