# Generated by Django 3.1.2 on 2021-01-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placelocation',
            name='city',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='placelocation',
            name='country',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='placelocation',
            name='street_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
