# Generated by Django 3.1.2 on 2020-10-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20201023_1013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='name_actor',
            new_name='NameActor',
        ),
        migrations.RenameModel(
            old_name='Place_Location',
            new_name='PlaceLocation',
        ),
        migrations.RenameModel(
            old_name='Place_Type',
            new_name='PlaceType',
        ),
        migrations.RenameModel(
            old_name='Type_Object',
            new_name='TypeObject',
        ),
    ]
