# Generated by Django 3.1.2 on 2021-01-31 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20210131_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='actor',
            name='source',
            field=models.ManyToManyField(blank=True, to='database.Source'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='caracteristic',
            name='objectCaracteristic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='database.object'),
        ),
        migrations.AlterField(
            model_name='caracteristic',
            name='source',
            field=models.ManyToManyField(blank=True, to='database.Source'),
        ),
        migrations.AlterField(
            model_name='collectiveactor',
            name='definition',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='collectiveactor',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='collectiveactor',
            name='source',
            field=models.ManyToManyField(blank=True, to='database.Source'),
        ),
        migrations.AlterField(
            model_name='date',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='detailcaracteristic',
            name='detailCaracteristicsObject',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='detailcaracteristic',
            name='validated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='energy',
            name='energy',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='energy',
            name='validated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='definition',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='modify',
            name='content',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='modify',
            name='table',
            field=models.CharField(blank=True, choices=[('Date', 'Date'), ('Quality', 'Quality'), ('SourceType', 'Sourcetype'), ('Author', 'Author'), ('Content', 'Content'), ('Url', 'Url'), ('Source', 'Source'), ('PlaceLocation', 'Placelocation'), ('PlaceType', 'Placetype'), ('Place', 'Place'), ('Knowledge', 'Knowledge'), ('CollectiveActor', 'Collectiveactor'), ('AbstractObject', 'Abstractobject'), ('Profession', 'Profession'), ('SocialActivity', 'Socialactivity'), ('SocialLink', 'Sociallink'), ('Actor', 'Actor'), ('NameActor', 'Nameactor'), ('DetailCaracteristic', 'Detailcaracteristic'), ('TypeObject', 'Typeobject'), ('Energy', 'Energy'), ('Object', 'Object'), ('Caracteristic', 'Caracteristic')], max_length=250),
        ),
        migrations.AlterField(
            model_name='modify',
            name='x_value',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='modify',
            name='y_value',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nameactor',
            name='actors',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='database.actor'),
        ),
        migrations.AlterField(
            model_name='nameactor',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='nameactor',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='object',
            name='definition',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='object',
            name='source',
            field=models.ManyToManyField(blank=True, to='database.Source'),
        ),
        migrations.AlterField(
            model_name='object',
            name='type_object',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='database.typeobject'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='placelocation',
            name='street_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='placetype',
            name='placeType',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='quality',
            name='definition',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='quality',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='socialactivity',
            name='definition',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='socialactivity',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='socialactivity',
            name='source',
            field=models.ManyToManyField(blank=True, to='database.Source'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.CharField(blank=True, choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('SISTER', 'Sister'), ('BROTHER', 'Brother'), ('FRIEND', 'Friend'), ('CO-WORKERS', 'Coworker')], max_length=50),
        ),
        migrations.AlterField(
            model_name='source',
            name='author',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='database.author'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='source',
            name='types',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='database.sourcetype'),
        ),
        migrations.AlterField(
            model_name='typeobject',
            name='typeObject',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='typeobject',
            name='validated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
