# Generated by Django 3.1.2 on 2021-01-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20210131_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameactor',
            name='source',
            field=models.ManyToManyField(blank=True, to='database.Source'),
        ),
    ]
