# Generated by Django 3.1.2 on 2021-01-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20210131_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modify',
            name='field_value',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
