# Generated by Django 3.1.2 on 2020-10-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20201023_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectiveactor',
            name='date',
        ),
        migrations.RemoveField(
            model_name='collectiveactor',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='collectiveactor',
            name='place',
        ),
        migrations.RemoveField(
            model_name='collectiveactor',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='collectiveactor',
            name='source',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_location',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_type',
        ),
        migrations.RemoveField(
            model_name='place',
            name='source',
        ),
        migrations.RemoveField(
            model_name='source',
            name='author',
        ),
        migrations.RemoveField(
            model_name='source',
            name='content',
        ),
        migrations.RemoveField(
            model_name='source',
            name='date',
        ),
        migrations.RemoveField(
            model_name='source',
            name='types',
        ),
        migrations.RemoveField(
            model_name='source',
            name='url',
        ),
    ]
