# Generated by Django 3.1.2 on 2021-02-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20210206_1322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modify',
            new_name='ModifyAttribute',
        ),
        migrations.AddField(
            model_name='abstractobject',
            name='objects',
            field=models.ManyToManyField(blank=True, to='database.Object'),
        ),
        migrations.AddField(
            model_name='actor',
            name='knowledge',
            field=models.ManyToManyField(blank=True, to='database.Knowledge'),
        ),
        migrations.AddField(
            model_name='collectiveactor',
            name='abstractObject',
            field=models.ManyToManyField(blank=True, to='database.AbstractObject'),
        ),
        migrations.AddField(
            model_name='placelocation',
            name='borough',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='url',
            name='definition',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='placelocation',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='placelocation',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
