# Generated by Django 3.1.2 on 2020-10-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20201026_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='duration_date',
            field=models.DurationField(blank=True),
        ),
    ]
