# Generated by Django 3.1.2 on 2020-10-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20201026_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
