# Generated by Django 3.1.2 on 2021-03-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='url',
        ),
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
