# Generated by Django 3.1.2 on 2020-10-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20201026_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='duration_date',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
