# Generated by Django 3.1.2 on 2021-03-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20210325_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='url',
            field=models.FileField(upload_to=''),
        ),
    ]
