# Generated by Django 3.1.2 on 2020-10-26 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_date_duration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractobject',
            name='quality',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='database.quality'),
        ),
    ]
