# Generated by Django 3.1.2 on 2021-03-25 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20210325_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
