# Generated by Django 3.1.2 on 2021-03-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_delete_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='fileType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
