# Generated by Django 3.1.2 on 2021-03-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20210325_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='types',
        ),
        migrations.AlterField(
            model_name='files',
            name='fileType',
            field=models.CharField(blank=True, choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Cao', 'Cao'), ('Image', 'Image')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='SourceType',
        ),
    ]
