# Generated by Django 3.1.2 on 2021-03-25 23:03

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20210325_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to=database.models.path),
        ),
    ]
