# Generated by Django 3.1.2 on 2021-04-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_auto_20210408_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=500)),
                ('repere_historique', models.CharField(blank=True, max_length=500)),
                ('ressource_date', models.DateField(blank=True, null=True)),
                ('localization', models.CharField(blank=True, max_length=250)),
                ('adress', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('mots_cles', models.CharField(blank=True, max_length=500)),
                ('ressource_source', models.CharField(blank=True, max_length=500)),
                ('editeur', models.CharField(blank=True, max_length=500)),
                ('droits', models.CharField(blank=True, max_length=500)),
                ('ressource_type', models.CharField(blank=True, max_length=500)),
                ('ressource_format', models.CharField(blank=True, max_length=500)),
                ('immatriculation', models.CharField(blank=True, max_length=500)),
                ('etude', models.CharField(blank=True, max_length=500)),
                ('auteur', models.CharField(blank=True, max_length=500)),
                ('date_etude', models.DateField(blank=True, null=True)),
                ('ressource_file', models.ManyToManyField(blank=True, to='database.Files')),
            ],
        ),
    ]
