# Generated by Django 3.1.2 on 2021-04-09 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_ressource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressource',
            name='ressource_file',
        ),
        migrations.AddField(
            model_name='ressource',
            name='ressource_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.files'),
        ),
    ]
