# Generated by Django 3.1.2 on 2021-04-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_auto_20210409_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='date_etude',
            field=models.CharField(blank=True, default='null', max_length=250),
        ),
    ]
