# Generated by Django 3.1.2 on 2020-10-26 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_auto_20201026_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='collectiveActors',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.collectiveactor'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='quality',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.quality'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='social',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.social'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='socialLink',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.sociallink'),
        ),
    ]
