# Generated by Django 3.1.2 on 2021-04-22 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_auto_20210422_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectiveactor',
            old_name='abstractObject',
            new_name='collective_abstractObject',
        ),
    ]
