# Generated by Django 3.1.2 on 2021-04-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_auto_20210422_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractobject',
            old_name='objects',
            new_name='ab_objects',
        ),
    ]
