# Generated by Django 3.1.2 on 2021-04-24 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_auto_20210422_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='actor',
            name='arrival_date',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='database.date'),
        ),
        migrations.AddField(
            model_name='actor',
            name='birth_date',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth', to='database.date'),
        ),
        migrations.AddField(
            model_name='actor',
            name='departure_date',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='database.date'),
        ),
    ]
