# Generated by Django 3.1.2 on 2020-10-26 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_auto_20201026_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(blank=True, default=None, null=True)),
                ('width', models.FloatField(blank=True, default=None, null=True)),
                ('height', models.FloatField(blank=True, default=None, null=True)),
                ('weight', models.FloatField(blank=True, default=None, null=True)),
                ('surface', models.FloatField(blank=True, default=None, null=True)),
                ('detail_caracteristics', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.detailcaracteristics')),
            ],
        ),
        migrations.RemoveField(
            model_name='object',
            name='caracteristics',
        ),
        migrations.DeleteModel(
            name='Caracteristics',
        ),
        migrations.AddField(
            model_name='caracteristic',
            name='nameCaracteristic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.object'),
        ),
    ]
