# Generated by Django 3.1.2 on 2021-05-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0037_auto_20210425_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, max_length=500)),
                ('wall', models.CharField(blank=True, max_length=500)),
                ('roof', models.CharField(blank=True, max_length=500)),
                ('floor', models.IntegerField(blank=True)),
                ('surface', models.IntegerField(blank=True)),
                ('light', models.CharField(blank=True, max_length=500)),
                ('materials', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.AddField(
            model_name='object',
            name='fk_typologie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.typologie'),
        ),
    ]
