# Generated by Django 3.1.2 on 2021-06-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_auto_20210504_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='actor',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
