# Generated by Django 3.1.2 on 2020-10-26 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_nameactor_typeofactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristic',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.source'),
        ),
    ]
