# Generated by Django 3.1.2 on 2020-10-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0039_caracteristic_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='socialLink',
        ),
        migrations.AddField(
            model_name='actor',
            name='socialLink',
            field=models.ManyToManyField(blank=True, related_name='_actor_socialLink_+', to='database.Actor'),
        ),
    ]
