# Generated by Django 3.1.2 on 2021-06-03 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0040_auto_20210603_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='place',
            new_name='living_place',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='addition_inf_date',
        ),
        migrations.AddField(
            model_name='actor',
            name='Catégorie',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme')], max_length=50),
        ),
        migrations.AddField(
            model_name='actor',
            name='Domain',
            field=models.CharField(blank=True, choices=[("Main d'oeuvre", 'Maine'), ('Oeuvres sociales', 'Oeuvressoc'), ('Formation', 'Formation')], max_length=50),
        ),
        migrations.AddField(
            model_name='actor',
            name='birth_place',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='birth_place', to='database.place'),
        ),
        migrations.AddField(
            model_name='actor',
            name='instruction_level',
            field=models.CharField(blank=True, choices=[('0', 'Zero'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('X', 'X')], max_length=50),
        ),
    ]
