# Generated by Django 3.1.2 on 2021-06-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0041_auto_20210603_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='Catégorie',
            field=models.CharField(blank=True, choices=[('Hommes', 'Hommes')], max_length=50),
        ),
    ]
