# Generated by Django 3.1.2 on 2021-06-03 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0042_auto_20210603_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='Catégorie',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='Domain',
            new_name='domain',
        ),
        migrations.AddField(
            model_name='actor',
            name='death_date',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='death_date', to='database.date'),
        ),
        migrations.AddField(
            model_name='actor',
            name='death_place',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='death_place', to='database.place'),
        ),
        migrations.AddField(
            model_name='actor',
            name='home_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='home_status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='actor',
            name='wedding_date',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wedding_date', to='database.date'),
        ),
        migrations.AddField(
            model_name='actor',
            name='wedding_lastName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='actor',
            name='wedding_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='actor',
            name='wedding_place',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wedding_place', to='database.place'),
        ),
    ]
