# Generated by Django 3.1.2 on 2021-06-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0043_auto_20210603_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='building',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
