# Generated by Django 3.1.2 on 2021-06-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0044_actor_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_place',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='actor',
            name='death_place',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='actor',
            name='wedding_place',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
