# Generated by Django 3.1.2 on 2020-10-27 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0044_auto_20201027_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='actorlinked',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='actorlinked',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.actor'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('SISTER', 'Sister'), ('BROTHER', 'Brother'), ('FRIEND', 'Friend'), ('CO-WORKERS', 'Coworker')], max_length=50),
        ),
    ]
