# Generated by Django 3.1.2 on 2021-06-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0045_auto_20210603_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Homme', 'Male'), ('Femme', 'Female'), ('Autre', 'Other')], max_length=50),
        ),
    ]
