# Generated by Django 3.1.2 on 2021-06-03 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0047_auto_20210603_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='profession',
        ),
        migrations.AddField(
            model_name='actor',
            name='profession',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='database.profession'),
        ),
    ]
