# Generated by Django 3.1.2 on 2020-10-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0047_auto_20201027_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcetypes',
            name='typesSource',
            field=models.CharField(max_length=100),
        ),
    ]
