# Generated by Django 3.1.2 on 2020-10-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0048_auto_20201028_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SourceTypes',
            new_name='SourceType',
        ),
    ]
