# Generated by Django 3.1.2 on 2021-06-03 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0050_auto_20210603_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='living_place',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='database.place'),
        ),
    ]
