# Generated by Django 3.1.2 on 2021-06-03 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0051_auto_20210603_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='date_source',
        ),
        migrations.AddField(
            model_name='source',
            name='date_source',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='database.date'),
        ),
    ]
