# Generated by Django 3.1.2 on 2021-06-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0052_auto_20210603_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='fileType',
            new_name='file_type',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='collectiveActors',
            new_name='collective_actors',
        ),
        migrations.RenameField(
            model_name='sociallink',
            old_name='actorlink',
            new_name='actor_link',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='conservationPlace',
            new_name='conservation_place',
        ),
        migrations.RemoveField(
            model_name='caracteristic',
            name='source',
        ),
        migrations.RemoveField(
            model_name='caracteristic',
            name='validated',
        ),
        migrations.RemoveField(
            model_name='date',
            name='source_date',
        ),
        migrations.RemoveField(
            model_name='detailcaracteristic',
            name='source',
        ),
        migrations.RemoveField(
            model_name='detailcaracteristic',
            name='validated',
        ),
        migrations.RemoveField(
            model_name='energy',
            name='source',
        ),
        migrations.RemoveField(
            model_name='energy',
            name='validated',
        ),
        migrations.RemoveField(
            model_name='quality',
            name='source_quality',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='date_etude',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='droits',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='editeur',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='etude',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='immatriculation',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='localization',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='mots_cles',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='repere_historique',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='ressource_date',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='ressource_file',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='ressource_format',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='ressource_source',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='ressource_type',
        ),
        migrations.RemoveField(
            model_name='typeobject',
            name='source',
        ),
        migrations.RemoveField(
            model_name='typeobject',
            name='validated',
        ),
        migrations.AddField(
            model_name='actor',
            name='father',
            field=models.ManyToManyField(blank=True, related_name='actor_father', to='database.Ressource'),
        ),
        migrations.AddField(
            model_name='object',
            name='father',
            field=models.ManyToManyField(blank=True, related_name='object_father', to='database.Ressource'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='actors',
            field=models.ManyToManyField(blank=True, to='database.Actor'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='field',
            field=models.CharField(blank=True, choices=[('Architecture', 'Architecture'), ('Production', 'Production'), ('Homme', 'Homme')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ressource',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ressource',
            name='objects',
            field=models.ManyToManyField(blank=True, to='database.Object'),
        ),
        migrations.AlterField(
            model_name='object',
            name='categorie',
            field=models.CharField(blank=True, choices=[('Architecture', 'Architecture'), ('Production', 'Production'), ('Hommes', 'Hommes'), ('Urbanisme', 'Urbanisme')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='description',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
