# Generated by Django 3.1.2 on 2021-06-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0053_auto_20210610_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ressource',
            old_name='actors',
            new_name='actors_son',
        ),
        migrations.RenameField(
            model_name='ressource',
            old_name='objects',
            new_name='objects_son',
        ),
    ]
