# Generated by Django 3.1.2 on 2021-06-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0055_auto_20210617_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='period',
            field=models.CharField(blank=True, choices=[('1er quart 19e siècle', 'Firstnine'), ('2e quart 19e siècle', 'Secondnine'), ('3e quart 19e siècle', 'Thirdnine'), ('4e quart 19e siècle', 'Fourthnine'), ('1er quart 20e siècle', 'Firsttwenty'), ('2e quart 20e siècle', 'Secondtwenty'), ('3e quart 20e siècle', 'Thirdtwenty'), ('4e quart 20e siècle', 'Fourthtwenty'), ('1er quart 21e siècle', 'Firsttwentyone')], max_length=200),
        ),
    ]
