# Generated by Django 3.1.2 on 2021-06-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0056_object_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='building',
        ),
        migrations.DeleteModel(
            name='Building_type',
        ),
    ]
