# Generated by Django 3.1.2 on 2021-06-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0057_auto_20210617_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='complement',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
