# Generated by Django 3.1.2 on 2021-06-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0058_date_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='field',
            field=models.CharField(blank=True, choices=[('Architecture', 'Architecture'), ('Production', 'Production'), ('Hommes', 'Hommes')], max_length=20, null=True),
        ),
    ]
