# Generated by Django 3.1.2 on 2021-01-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0059_research'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Research',
        ),
    ]
