# Generated by Django 3.1.2 on 2021-06-21 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0059_auto_20210619_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='domain',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birth_place',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='birth_place', to='database.place'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='death_place',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='death_place', to='database.place'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='domain',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='actor',
            name='wedding_place',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wedding_place', to='database.place'),
        ),
    ]
