# Generated by Django 3.1.2 on 2021-01-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0060_delete_research'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcetype',
            old_name='typesSource',
            new_name='typeSource',
        ),
    ]
