# Generated by Django 3.1.2 on 2021-06-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0062_auto_20210626_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='typologie',
            name='cover',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='typologie',
            name='floor',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
