# Generated by Django 3.1.2 on 2021-06-27 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0064_auto_20210627_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='abstract_object',
        ),
        migrations.AddField(
            model_name='object',
            name='abstract_object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.abstractobject'),
        ),
        migrations.RemoveField(
            model_name='object',
            name='date',
        ),
        migrations.AddField(
            model_name='object',
            name='date',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.date'),
        ),
        migrations.RemoveField(
            model_name='object',
            name='place',
        ),
        migrations.AddField(
            model_name='object',
            name='place',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.place'),
        ),
    ]
