# Generated by Django 3.1.2 on 2021-06-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0067_auto_20210627_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='typologie',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
