# Generated by Django 3.1.2 on 2021-06-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0068_typologie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='conservation_state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='object',
            name='machine',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='object',
            name='materials',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='object',
            name='precision_conservation_state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
