# Generated by Django 3.1.2 on 2021-06-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0069_auto_20210627_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='constructor_inscription',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='object',
            name='constructor_precision',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
