# Generated by Django 3.1.2 on 2021-06-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0070_auto_20210627_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='author',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='source',
            name='editor',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
