# Generated by Django 3.1.2 on 2021-06-27 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0071_auto_20210627_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='brand',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='database.abstractobject'),
        ),
    ]
