# Generated by Django 3.1.2 on 2021-06-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0072_actor_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='brand',
            new_name='abstract_object',
        ),
    ]
