# Generated by Django 3.1.2 on 2021-06-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0073_auto_20210627_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
