# Generated by Django 3.1.2 on 2021-06-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0074_auto_20210627_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='materials',
            new_name='material',
        ),
    ]
