# Generated by Django 3.1.2 on 2020-12-11 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20201211_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='discipline',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.discipline'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='researchEstablishment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.researchestablishment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='researchField',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.researchfield'),
        ),
    ]
