# Generated by Django 3.1.2 on 2020-12-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20201211_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='discipline',
            new_name='disciplineFK',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='researchEstablishment',
            new_name='researchEstablishmentFK',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='researchField',
            new_name='researchFieldFK',
        ),
    ]
